Odev.Admin/Controllers/SiteSettingsController.cs
using Odev.Domain.Environments;
using Odev.Domain.Validations;
using Odev.Domain.ViewModels;
using Odev.Services.DbServices;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Odev.Admin.Controllers
{
    public class SiteSettingsController : BaseController
    {
        private readonly SiteSettingServices _siteSettingsServices;
        private readonly UserTypeServices _userTypeServices;
        private UserTypeViewModel _userTypeViewModel;

        private readonly string ViewList = "List";
        private readonly string ViewForm = "Form";

        public SiteSettingsController()
        {
            _siteSettingsServices = new SiteSettingServices(_unitOfWork);
            _userTypeServices = new UserTypeServices(_unitOfWork);
        }

        public ActionResult Index()
        {
            SessionKontrol();
            if (_user != null)
            {
                _userTypeViewModel = _userTypeServices.Get(_user.UserTypeId);
                if (_userTypeViewModel.SiteSettingTransactions)
                {
                    var viewModel = _siteSettingsServices.GetAll();
                    return View(ViewList, viewModel);
                }
                return RedirectToAction("Index", "Home");
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }

        public ActionResult New()
        {
            SessionKontrol();
            if (_user != null)
            {
                _userTypeViewModel = _userTypeServices.Get(_user.UserTypeId);
                if (_userTypeViewModel.SubSiteSettingTransactions)
                {
                    return View(ViewForm, new SiteSettingViewModel { IsActive = true });
                }
                return RedirectToAction("Index", "Home");
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }

        public ActionResult Edit(Guid id)
        {
            SessionKontrol();
            if (_user != null)
            {
                _userTypeViewModel = _userTypeServices.Get(_user.UserTypeId);
                if (_userTypeViewModel.SubSiteSettingTransactions)
                {
                    var viewModel = _siteSettingsServices.Get(id);
                    return View(ViewForm, viewModel);
                }
                return RedirectToAction("Index", "Home");
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }

        public JsonResult SitesettingList()
        {
            var serviceResult = _siteSettingsServices.GetAll().ToList();
            return Json(serviceResult, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Delete(Guid id)
        {
            SessionKontrol();
            if (_user != null)
            {
                _userTypeViewModel = _userTypeServices.Get(_user.UserTypeId);
                if (_userTypeViewModel.SubSiteSettingTransactions)
                {
                    var result = _siteSettingsServices.Get(id);
                    result.UpdatedUserId = _user.UpdatedUserId;
                    _siteSettingsServices.Update(result);
                    _siteSettingsServices.Delete(id);
                    _unitOfWork.SaveChanges();

                    return RedirectToAction("Index");
                }
                return RedirectToAction("Index", "Home");
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }

        public ActionResult Save(SiteSettingViewModel viewModel, HttpPostedFileBase logo)
        {
            SessionKontrol();
            if (_user != null)
            {
                _userTypeViewModel = _userTypeServices.Get(_user.UserTypeId);
                if (_userTypeViewModel.SubSiteSettingTransactions)
                {
                    var isValid = Validate(viewModel, new SiteSettingValidator(), ModelState);
                    if (isValid)
                    {
                        viewModel.UpdatedUserId = _user.UpdatedUserId;
                        if (logo != null)
                        {
                            var extension = Path.GetExtension(logo.FileName);
                            string fileName = Guid.NewGuid() + extension;
                            var urlPath = Path.Combine(Server.MapPath(Globals.FileURL), fileName);
                            logo.SaveAs(urlPath);
                            viewModel.Logo = fileName;
                        }

                        if (viewModel.Id == Guid.Empty)
                        {
                            _siteSettingsServices.Add(viewModel);
                        }
                        else
                        {
                            _siteSettingsServices.Update(viewModel);
                        }

                        _unitOfWork.SaveChanges();
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        return View(ViewForm, viewModel);
                    }
                }
                return RedirectToAction("Index", "Home");
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }
    }
}

Odev.Admin/Views/SiteSettings/Form.cshtml
@using Odev.Domain.ViewModels
@using Odev.Domain.Enums

@model SiteSettingViewModel

@{
    ViewBag.Title = "İletişim Ayar Form";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@Html.Partial("_TopPartialView",
    new TopPartialViewModel
    {
        Title = "İletişim Ayar Form",
        ListUrl = Url.Action("Index", "SiteSettings")
    })

<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-sm-12">
            <div class="ibox ">
                <div class="ibox-content">
                    @using (Html.BeginForm("Save", "SiteSettings", FormMethod.Post, new { @class = "form-horizontal", @enctype = "multipart/form-data" }))
                    {
                        @Html.HiddenFor(x => x.Id)

                        <div class="form-group  row">
                            @Html.LabelFor(x => x.Language, new { @class = "col-sm-2 col-form-label" })
                            <div class="col-sm-10">
                                @Html.DropDownListFor(x => x.Language, EnumHelper.GetSelectList(typeof(LanguageSelection)), "Lütfen Dil Seçiniz !!", new { @class = "form-control", @required = "required" })
                                <div style="color:red;">@Html.ValidationMessageFor(x => x.Language)</div>
                            </div>
                        </div>

                        <div class="hr-line-dashed"></div>

                        <div class="form-group  row">
                            @Html.LabelFor(x => x.Email, new { @class = "col-sm-2 col-form-label" })
                            <div class="col-sm-10">
                                @Html.TextBoxFor(x => x.Email, new { @class = "form-control" })
                                <div style="color:red;">@Html.ValidationMessageFor(x => x.Email)</div>
                            </div>
                        </div>

                        <div class="hr-line-dashed"></div>

                        <div class="form-group  row">
                            @Html.LabelFor(x => x.Phone, new { @class = "col-sm-2 col-form-label" })
                            <div class="col-sm-10">
                                @Html.TextBoxFor(x => x.Phone, new { @class = "form-control" })
                                <div style="color:red;">@Html.ValidationMessageFor(x => x.Phone)</div>
                            </div>
                        </div>

                        <div class="hr-line-dashed"></div>

                        <div class="form-group  row">
                            @Html.LabelFor(x => x.Fax, new { @class = "col-sm-2 col-form-label" })
                            <div class="col-sm-10">
                                @Html.TextBoxFor(x => x.Fax, new { @class = "form-control" })
                                <div style="color:red;">@Html.ValidationMessageFor(x => x.Fax)</div>
                            </div>
                        </div>

                        <div class="hr-line-dashed"></div>

                        <div class="form-group  row">
                            @Html.LabelFor(x => x.Adres, new { @class = "col-sm-2 col-form-label" })
                            <div class="col-sm-10">
                                @Html.TextAreaFor(x => x.Adres, new { @class = "form-control", @rows = 5 })
                                <div style="color:red;">@Html.ValidationMessageFor(x => x.Adres)</div>
                            </div>
                        </div>

                        <div class="hr-line-dashed"></div>

                        <div class="form-group  row">
                            @Html.LabelFor(x => x.Maps, new { @class = "col-sm-2 col-form-label" })
                            <div class="col-sm-10">
                                @Html.TextBoxFor(x => x.Maps, new { @class = "form-control" })
                                <div style="color:red;">@Html.ValidationMessageFor(x => x.Maps)</div>
                            </div>
                        </div>

                        <div class="hr-line-dashed"></div>

                        <div class="form-group  row">
                            @Html.LabelFor(x => x.Logo, new { @class = "col-sm-2 col-form-label" })
                            <div class="col-sm-10">
                                <input type="file" id="image" class="dropify" name="logo" data-default-file="/Assets/Library/@Model.Logo">
                                <div style="color:red;">@Html.ValidationMessageFor(x => x.Logo)</div>
                            </div>
                        </div>

                        <div class="hr-line-dashed"></div>

                        <div class="form-group  row">
                            @Html.LabelFor(x => x.Facebook, new { @class = "col-sm-2 col-form-label" })
                            <div class="col-sm-10">
                                @Html.TextBoxFor(x => x.Facebook, new { @class = "form-control" })
                                <div style="color:red;">@Html.ValidationMessageFor(x => x.Facebook)</div>
                            </div>
                        </div>

                        <div class="hr-line-dashed"></div>

                        <div class="form-group  row">
                            @Html.LabelFor(x => x.Twitter, new { @class = "col-sm-2 col-form-label" })
                            <div class="col-sm-10">
                                @Html.TextBoxFor(x => x.Twitter, new { @class = "form-control" })
                                <div style="color:red;">@Html.ValidationMessageFor(x => x.Twitter)</div>
                            </div>
                        </div>

                        <div class="hr-line-dashed"></div>

                        <div class="form-group  row">
                            @Html.LabelFor(x => x.Instagram, new { @class = "col-sm-2 col-form-label" })
                            <div class="col-sm-10">
                                @Html.TextBoxFor(x => x.Instagram, new { @class = "form-control" })
                                <div style="color:red;">@Html.ValidationMessageFor(x => x.Instagram)</div>
                            </div>
                        </div>

                        <div class="hr-line-dashed"></div>

                        <div class="form-group  row">
                            @Html.LabelFor(x => x.Youtube, new { @class = "col-sm-2 col-form-label" })
                            <div class="col-sm-10">
                                @Html.TextBoxFor(x => x.Youtube, new { @class = "form-control" })
                                <div style="color:red;">@Html.ValidationMessageFor(x => x.Youtube)</div>
                            </div>
                        </div>

                        <div class="hr-line-dashed"></div>

                        <div class="form-group row">
                            <div class="col-sm-4 col-sm-offset-2">
                                <button class="btn btn-warning btn-sm" type="reset">Temizle</button>
                                <button class="btn btn-primary btn-sm" type="submit">Kaydet</button>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>
<!-- end row -->

@section script{
    <script>
        $('.dropify').dropify();

    </script>
}

Odev.Admin/Views/SiteSettings/List.cshtml
@using Odev.Domain.ViewModels
@using Odev.Domain.Helpers

@model IQueryable<SiteSettingViewModel>

@{
    ViewBag.Title = "İletişim Ayar Listesi";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@Html.Partial("_TopPartialView",
    new TopPartialViewModel
    {
        Title = "İletişim Ayar Listesi",
        ListUrl = null
    })

<div class="wrapper wrapper-content animated fadeInRight">
    @if (Model.ToList().Where(x => x.IsActive == true).Count() == 0)
    {
        <div class="row">
            <div class="col-lg-12">
                <div class="alert alert-success" role="alert">
                    İletişim Ayar Listesi Boş
                </div>
            </div>
        </div>
    }
    else
    {
        <div class="row">
            <div class="col-lg-12">
                <div class="ibox ">
                    @if (TempData["ErrorMessage"] != null)
                    {
                        <div class="alert alert-danger" role="alert"><strong>@TempData["ErrorMessage"]</strong></div>
                    }
                    <div class="ibox-title">
                        <a href="@Url.Action("New","SiteSettings")" class="btn btn-primary">Yeni İletişim Ayarı</a>
                    </div>
                    <div class="ibox-content">
                        <div class="table-responsive">
                            <table class="table table-striped table-bordered table-hover dataTables-example">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>Email</th>
                                        <th>Telefon</th>
                                        <th>Fax</th>
                                        <th>Adres</th>
                                        <th>Dil</th>
                                        <th>İşlemler</th>
                                    </tr>
                                </thead>
                                <tbody id="siteSettingsTablo">
                                    @foreach (var item in Model.ToList())
                                    {
                                        <tr>
                                            <td>@item.Id</td>
                                            <td>@item.Email</td>
                                            <td>@item.Phone</td>
                                            @if (string.IsNullOrEmpty(item.Fax))
                                            {
                                                <td> - </td>
                                            }
                                            else
                                            {
                                                <td>@item.Fax</td>
                                            }
                                            <td>@item.Adres</td>
                                            <td>@item.Language.GetDisplayName()</td>
                                            <td>
                                                @Html.ActionLink("Düzenle", "Edit", "SiteSettings", new { id = item.Id }, new { @class = "btn btn-warning" })
                                                <button data-id='@item.Id' class="btn btn-danger">Sil</button>
                                            </td>
                                        </tr>
                                    }

                                </tbody>
                                <tfoot>
                                    <tr>
                                        <th>#</th>
                                        <th>Email</th>
                                        <th>Telefon</th>
                                        <th>Fax</th>
                                        <th>Adres</th>
                                        <th>Dil</th>
                                        <th>İşlemler</th>
                                    </tr>
                                </tfoot>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
</div>
<!-- end row -->

@section script{
    <link href="/Assets/css/plugins/sweetalert/sweetalert.css" rel="stylesheet">
    <script src="/Assets/js/plugins/sweetalert/sweetalert.min.js"></script>

    <script>
        $(document).ready(function () {
            var dataTable = $('.dataTables-example').DataTable({
                pageLength: 25,
                responsive: true,
                dom: '<"html5buttons"B>lTfgitp',
                buttons: [
                    {
                        extend: 'excel',
                        title: 'İletişim Ayar Listesi',
                        exportOptions: {
                            columns: [0, 1, 2, 3, 4, 5]
                        } },
                    {
                        extend: 'pdf',
                        title: 'İletişim Ayar Listesi',
                        exportOptions: {
                            columns: [0, 1, 2, 3, 4, 5]
                        } },
                    {
                        extend: 'print',
                        customize: function (win) {
                            $(win.document.body).addClass('white-bg');
                            $(win.document.body).css('font-size', '10px');
                            $(win.document.body).find('table')
                                .addClass('compact')
                                .css('font-size', 'inherit');
                        },
                        exportOptions: {
                            columns: [0, 1, 2, 3, 4, 5]
                        }
                    }
                ],
                select: true,
                columnDefs: [
                    { orderable: false, targets: 6 }
                ],
                lengthMenu: [
                    [10, 25, 50, -1],
                    ['10', '25', '50', 'Tümü']
                ],
                "language": {
                    "lengthMenu": "Sayfa başına _MENU_ kayıt göster",
                    "info": "_TOTAL_ kayıttan _START_ - _END_ arası gösteriliyor",
                    "infoEmpty": "Gösterilecek kayıt yok",
                    "infoFiltered": "(_MAX_ kayıt içerisinden filtrelenen)",
                    "search": "Ara:",
                    "paginate": {
                        "first": "İlk",
                        "last": "Son",
                        "next": "Sonraki",
                        "previous": "Önceki"
                    }
                }
            });

            $("#siteSettingsTablo").on("click", "button", function () {
                var siteSettingsId = $(this).data("id");

                var siteSettings = {
                    Id: siteSettingsId,
                };

                swal({
                    title: "Emin misiniz?",
                    type: "warning",
                    showCancelButton: true,
                    confirmButtonColor: "#DD6B55",
                    confirmButtonText: "Sil",
                    cancelButtonText: "İptal",
                    closeOnConfirm: false,
                    closeOnCancel: false,

                },
                    function (isConfirm) {
                        if (isConfirm) {
                            $.ajax({
                                type: "post",
                                url: "/SiteSettings/Delete/",
                                data: siteSettings,
                                success: function (mahmt) {
                                    if (mahmt) {
                                        swal({
                                            title: "Silme işlemi başarılı?",
                                            closeOnConfirm: false,

                                        });
                                        location.reload();
                                    }
                                    else {
                                        alert("Bir hata oluştu")
                                    }
                                }
                            });
                        } else {
                            swal({
                                title: "İptal Edildi",
                                type: "error",
                                confirmButtonText: "Tamam",
                                closeOnConfirm: false,

                            });
                        }
                    });
            });
        });
    </script>
}